name: Run Python Tests

on:
  push:
    branches:
      - main  # Überwacht den main-Branch (anpassen, falls du einen anderen Branch verwendest)
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Ersetze mit der benötigten Python-Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt  # Erforderlich, wenn du eine requirements.txt hast

    - name: Run tests
      run: |
        pytest LB1/tests --maxfail=5 --disable-warnings --tb=short
